### ISSUE TITLE
Rooster Money becomes unavailable at the start of a new week

### ISSUE THREAD

**Issue by pantherale0** [pantherale0/pyroostermoney#17]
### System Health details

NA

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Integration stops responding after some time with the following error logged:

This error originated from a custom integration.

Logger: custom_components.rooster_money.update_coordinator
Source: helpers/update_coordinator.py:229
Integration: Natwest Rooster Money (documentation, issues)
First occurred: 28 August 2023 at 00:00:48 (6 occurrences)
Last logged: 00:00:37

Error fetching Rooster Money data:

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
NA
```

**Comment by pantherale0** [comment]
Additional error on reload:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/rooster_money/__init__.py:43
Integration: Natwest Rooster Money (documentation, issues)
First occurred: 00:29:01 (1 occurrences)
Last logged: 00:29:01

Error setting up entry Natwest Rooster Money for rooster_money
Traceback (most recent call last):
  File "/config/custom_components/rooster_money/__init__.py", line 32, in async_setup_entry
    rooster = await RoosterMoney.create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyroostermoney/roostermoney.py", line 43, in create
    await self.update()
  File "/usr/local/lib/python3.11/site-packages/pyroostermoney/roostermoney.py", line 52, in update
    await self._update_children()
  File "/usr/local/lib/python3.11/site-packages/pyroostermoney/roostermoney.py", line 70, in _update_children
    child = await ChildAccount.create(child.get("userId"),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyroostermoney/child/__init__.py", line 66, in create
    await self.update()
  File "/usr/local/lib/python3.11/site-packages/pyroostermoney/child/__init__.py", line 78, in update
    await self.get_active_allowance_period()
  File "/usr/local/lib/python3.11/site-packages/pyroostermoney/child/__init__.py", line 116, in get_active_allowance_period
    raise LookupError("No allowance period found")
LookupError: No allowance period found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rooster_money/__init__.py", line 43, in async_setup_entry
    raise CannotConnect
custom_components.rooster_money.CannotConnect

**Comment by pantherale0** [comment]
This happens because NatWest hasn't built a new allowance period for the current week, will need to update the `update` function so that it ignores these errors and doesn't update the data in this situation
